#the classifier to use
classifier : |
  ensemble.RandomForestRegressor(
    n_estimators=30,
    max_features='sqrt',
    n_jobs=-1,
    max_depth=12,
  )


# randomly sample the data if you dont want to use the whole set
n_signal : 100000

# define th number of cross validations to perform
n_cross_validations : 5

training_variables:
   - Size
   - Length
   - Width
   - numIslands
   - Leakage
   - m3l
   - m3t
   - Disp
   - Timespread
   - arrivalTimeMean
   - ConcCore
