# seed for the random number generators, to make things reproducible
seed: 0


# telescope_type_key: telescope_type_name
telescope_events_key: telescope_events
array_events_key: array_events
runs_key: runs


multiple_telescopes: True


# config for the energy regression
energy:
  regressor : |
    ensemble.RandomForestRegressor(
      n_estimators=20,
      max_features='sqrt',
      n_jobs=1,
      max_depth=8,
    )


  target_column: mc_energy

  # define the number of cross validations to perform
  n_cross_validations : 3

  # Define the name of the category you want to find.
  # The default is 'gamma_energy_prediction'.
  output_name: gamma_energy_prediction

  # Define the name of the column that contains the name of the telescope in case you're working
  # with mulitple telescopes and telescope types
  telescope_type_key: telescope_type_name

  features:
    - num_triggered_telescopes
    - width
    - length
    - skewness
    - kurtosis
    - intensity
    - total_intensity
    - num_triggered_lst
    - num_triggered_mst
    - num_triggered_sst

  feature_generation:
    needed_columns:
      - width
      - length
      - intensity
    features:
      area: width * length
      width_length: 1 - (width / length)
      log_size: log(intensity)
      log_size_area: log(intensity) / (width * length)


# config for the g/h separation
separator:
  classifier : |
    ensemble.RandomForestClassifier(
        n_estimators=20,
        max_features='sqrt',
        n_jobs=1,
        max_depth=8,
        criterion='entropy',
    )



  n_cross_validations : 3

  multiple_telescopes: True

  calibrate_classifier: True

  features:
    - num_triggered_telescopes
    - width
    - length
    - skewness
    - kurtosis
    - intensity
    - total_intensity
    - num_triggered_lst
    - num_triggered_mst
    - num_triggered_sst


  feature_generation:
    needed_columns:
      - width
      - length
      - intensity
    features:
      area: width * length
      width_length: 1 - (width / length)
      log_size: log(intensity)
      log_size_area: log(intensity) / (width * length)
